apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: spog-trustification-hpto
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: spog-trustification-hpto
    app.kubernetes.io/part-of: trustification-1
  name: spog-trustification-hpto
spec:
  ports:
  - name: "3001"
    port: 3001
    targetPort: 3001
  selector:
    app.kubernetes.io/instance: spog-trustification-hpto
status:
  loadBalancer: {}
